=== epam/edp-ddm-architecture/en/platform/1.9.7/arch/_attachments/architecture/registry/administrative/regulation-management/admin-portal/DataModelSnapshotSchema-table.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/$defs/ddmTable",
  "$defs": {
    "required": [
      "ddmTables"
    ],
    "ddmTable": {
      "type": "object",
      "description": "Type of the table entity",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the table"
        },
        "historyFlag": {
          "type": [
            "boolean",
            "null"
          ],
          "description": "Flag that indicates if table history has to be saved"
        },
        "objectReference": {
          "type": [
            "boolean",
            "null"
          ],
          "description": "Flag that indicates if table is an object reference to a subject"
        },
        "description": {
          "type": "string",
          "description": "Description (remarks) of the table"
        },
        "columns": {
          "type": "object",
          "description": "Map of table columns",
          "additionalProperties": {
            "$ref": "#/$defs/ddmColumn"
          }
        },
        "foreignKeys": {
          "type": "object",
          "description": "Map of table foreign keys",
          "additionalProperties": {
            "$ref": "#/$defs/ddmForeignKey"
          }
        },
        "primaryKey": {
          "$ref": "#/$defs/ddmIndex",
          "description": "Table primary key"
        },
        "uniqueConstraints": {
          "type": "object",
          "description": "Map of table unique constraints (indices)",
          "additionalProperties": {
            "$ref": "#/$defs/ddmIndex"
          }
        },
        "indices": {
          "type": "object",
          "description": "Map of table other indices",
          "additionalProperties": {
            "$ref": "#/$defs/ddmIndex"
          }
        }
      },
      "required": [
        "name",
        "historyFlag",
        "objectReference",
        "description",
        "columns",
        "foreignKeys",
        "primaryKey",
        "uniqueConstraints",
        "indices"
      ]
    },
    "ddmColumn": {
      "type": "object",
      "description": "Type of the column entity",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the table column"
        },
        "description": {
          "type": "string",
          "description": "Description (remarks) of the table column"
        },
        "type": {
          "type": "string",
          "$comment": "Should be enum",
          "description": "Table column type"
        },
        "defaultValue": {
          "type": [
            "string",
            "null"
          ],
          "description": "Table column default value computed"
        },
        "notNullFlag": {
          "type": "boolean",
          "description": "Table column not null flag"
        },
        "tableName": {
          "type": "string",
          "description": "Table name"
        }
      },
      "required": [
        "name",
        "description",
        "type",
        "defaultValue",
        "notNullFlag",
        "tableName"
      ]
    },
    "ddmForeignKey": {
      "type": "object",
      "description": "Type of the foreign key entity",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the table foreign key"
        },
        "targetTable": {
          "type": "string",
          "description": "Name of the foreign key target table"
        },
        "sourceTable": {
          "type": "string",
          "description": "Name of the foreign key source table"
        },
        "columnPairs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ddmForeignKey/$nestedDefs/columnPair"
          }
        }
      },
      "required": [
        "name",
        "targetTable",
        "sourceTable",
        "columnPairs"
      ],
      "$nestedDefs": {
        "columnPair": {
          "type": "object",
          "description": "Type of the foreign key column pair entity",
          "properties": {
            "sourceColumnName": {
              "type": "string",
              "description": "Name of source column in foreign key relation"
            },
            "targetColumnName": {
              "type": "string",
              "description": "Name of target column in foreign key relation"
            }
          },
          "required": [
            "sourceColumnName",
            "targetColumnName"
          ]
        }
      }
    },
    "ddmIndex": {
      "type": "object",
      "description": "Type of the index entity",
      "properties": {
        "name": {
          "type": "string",
          "description": "Table index name"
        },
        "tableName": {
          "type": "string",
          "description": "Table name"
        },
        "columns": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ddmIndex/$nestedDefs/column"
          }
        }
      },
      "required": [
        "name",
        "tableName",
        "columns"
      ],
      "$nestedDefs": {
        "column": {
          "type": "object",
          "description": "Type of the index column entity",
          "properties": {
            "name": {
              "type": "string",
              "description": "Name of the index column"
            },
            "sorting": {
              "type": "string",
              "description": "Index column sorting",
              "enum": [
                "ASC",
                "DESC",
                "NONE"
              ]
            }
          },
          "required": [
            "name",
            "sorting"
          ]
        }
      }
    }
  }
}

=== epam/edp-ddm-architecture/ua/platform/1.9.10/arch/_attachments/architecture/registry/administrative/regulation-management/admin-portal/table-example.json
{
  "name": "application_type",
  "historyFlag": null,
  "objectReference": null,
  "description": "Довідник типів заяв",
  "columns": {
    "name": {
      "name": "name",
      "description": "Тип заяви",
      "type": "text",
      "defaultValue": null,
      "notNullFlag": true,
      "tableName": "application_type"
    },
    "application_type_id": {
      "name": "application_type_id",
      "description": "Ідентифікатор типів заяв",
      "type": "uuid",
      "defaultValue": "uuid_generate_v4()",
      "notNullFlag": true,
      "tableName": "application_type"
    },
    "constant_code": {
      "name": "constant_code",
      "description": "Символьна константа",
      "type": "text",
      "defaultValue": null,
      "notNullFlag": true,
      "tableName": "application_type"
    }
  },
  "foreignKeys": {},
  "primaryKey": {
    "name": "pk_application_type_id",
    "columns": [
      {
        "name": "application_type_id",
        "sorting": "ASC"
      }
    ],
    "tableName": "application_type"
  },
  "uniqueConstraints": {
    "application_type_name_key": {
      "name": "application_type_name_key",
      "columns": [
        {
          "name": "name",
          "sorting": "ASC"
        }
      ],
      "tableName": "application_type"
    }
  },
  "indices": {}
}
